---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: nyamnyam
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker.io/alrk/nyamnyam-config-server:0.01
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            - name: SPRING_APPLICATION_NAME
              value: config-server
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/alrk14567/nyamnyam-secret-server.git # HTTPS로 변경
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: main
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
              value: '{cipher}b1134c8b57c79d5fa19c6d6d32fc82f7697cc763866b8c0d42337cbdb4f16e3f28836c62ce1d3696979f109ca75ed1d5' # 암호화된 username
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
              value: '{cipher}42ab9480a3eeafe70e10a3b4b788795a1894c57403bf36968dd154beb023fd65e9f21f3ea35f0a86d364a1783fcb8f2db19ee3df6316e125cb3e68cc94e16c63' # 암호화된 Personal Access Token
          volumeMounts:
            - name: config-volume
              mountPath: /app/config  # 설정 파일을 마운트할 경로
      volumes:
        - name: config-volume
          configMap:
            name: config-server
      imagePullSecrets:
        - name: nyamnyam-regcred  # 이미지 풀 비밀 이름, 맞는지 확인
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: nyamnyam
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: config-server