---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: nyamnyam # 네임스페이스 이름
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: docker.io/alrk/nyamnyam-gateway-server:latest # Gateway 서버 이미지 경로
          ports:
            - containerPort: 8000 # Gateway 서버 기본 포트
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server.nyamnyam.svc.cluster.local/eureka/ # Eureka 서버 주소
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server.nyamnyam.svc.cluster.local:8888 # Config 서버 주소
          volumeMounts:
            - name: config-volume
              mountPath: /app/config # Config 파일 경로 마운트
      volumes:
        - name: config-volume
          configMap:
            name: gateway-server # ConfigMap 이름, 필요 시 수정
      imagePullSecrets:
        - name: nyamnyam-regcred # 이미지 풀 비밀 이름
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: nyamnyam # 네임스페이스 이름
spec:
  type: LoadBalancer # 외부에서 접근할 수 있도록 LoadBalancer로 설정
  ports:
    - protocol: TCP
      port: 80 # 외부에서 접근하는 포트
      targetPort: 8000 # 컨테이너 내부 포트
  selector:
    app: gateway-server
