apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: nyamnyam
data:
  init-script.js: |
    // MongoDB가 시작되면 이 스크립트를 실행하여 사용자 생성 및 데이터 삽입
    db.createUser({
        user: "root",
        pwd: "1q2w3e4r",
        roles: [{ role: "readWrite", db: "test" }]
    });
