apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: nyamnyam
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongo
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "512m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"  # 직접 설정한 사용자 이름
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "1q2w3e4r"  # 직접 설정한 비밀번호
            - name: MONGO_INITDB_DATABASE
              value: "test"  # 초기 데이터베이스 이름
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: nyamnyam-mongodb-pvc
        - name: init-scripts
          configMap:
            name: mongodb-init-script
      imagePullSecrets:
        - name: nyamnyam-regcred

---
apiVersion: v1
kind: Service
metadata:
  name: nyamnyam-mongodb-service
  namespace: nyamnyam
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
