apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyamnyam-api-ingress
  namespace: nyamnyam
spec:
  tls:
    - hosts:
        - kidonapi.nyamnyam.kr
      secretName: nyamnyam-key
  ingressClassName: nginx
  rules:
    - host: kidonapi.nyamnyam.kr
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-server
                port:
                  number: 8000